# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: delf/protos/box.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='delf/protos/box.proto',
  package='delf.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x64\x65lf/protos/box.proto\x12\x0b\x64\x65lf.protos\"a\n\x03\x42ox\x12\x0c\n\x04ymin\x18\x01 \x01(\x02\x12\x0c\n\x04xmin\x18\x02 \x01(\x02\x12\x0c\n\x04ymax\x18\x03 \x01(\x02\x12\x0c\n\x04xmax\x18\x04 \x01(\x02\x12\r\n\x05score\x18\x05 \x01(\x02\x12\x13\n\x0b\x63lass_index\x18\x06 \x01(\x05\"&\n\x05\x42oxes\x12\x1d\n\x03\x62ox\x18\x01 \x03(\x0b\x32\x10.delf.protos.Box')
)




_BOX = _descriptor.Descriptor(
  name='Box',
  full_name='delf.protos.Box',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ymin', full_name='delf.protos.Box.ymin', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xmin', full_name='delf.protos.Box.xmin', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ymax', full_name='delf.protos.Box.ymax', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xmax', full_name='delf.protos.Box.xmax', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='delf.protos.Box.score', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='class_index', full_name='delf.protos.Box.class_index', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=135,
)


_BOXES = _descriptor.Descriptor(
  name='Boxes',
  full_name='delf.protos.Boxes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='box', full_name='delf.protos.Boxes.box', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=175,
)

_BOXES.fields_by_name['box'].message_type = _BOX
DESCRIPTOR.message_types_by_name['Box'] = _BOX
DESCRIPTOR.message_types_by_name['Boxes'] = _BOXES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Box = _reflection.GeneratedProtocolMessageType('Box', (_message.Message,), dict(
  DESCRIPTOR = _BOX,
  __module__ = 'delf.protos.box_pb2'
  # @@protoc_insertion_point(class_scope:delf.protos.Box)
  ))
_sym_db.RegisterMessage(Box)

Boxes = _reflection.GeneratedProtocolMessageType('Boxes', (_message.Message,), dict(
  DESCRIPTOR = _BOXES,
  __module__ = 'delf.protos.box_pb2'
  # @@protoc_insertion_point(class_scope:delf.protos.Boxes)
  ))
_sym_db.RegisterMessage(Boxes)


# @@protoc_insertion_point(module_scope)
